/* WhatCoin — CactusByte Demo & Help */
(()=> {
  if(window.__whatCoinHelpInstalled)return;
  window.__whatCoinHelpInstalled=true;
  const V='1',SEEN='whatcoin_demo_seen:'+V,HIDE='whatcoin_demo_hide:'+V;
  const steps=[
    ['Identify the coin','Choose the year and denomination first. The denomination list changes to match the selected year.'],
    ['Describe what you can support','Choose the mint mark and the closest condition, toning, or variety description based on the actual coin.'],
    ['Treat grade as a major variable','Set the P-1 to MS-70 slider carefully. Unless the coin is professionally certified, the grade is still your estimate.'],
    ['Photo input is not part of valuation yet','The current screen has a Visual Evidence picker, but the present valuation request does not analyze that selected image.'],
    ['Run the estimate','Complete the required access field, then tap Query Market Valuation. The app returns an estimated value and explanation from its configured analysis service.'],
    ['Cross-check before acting','Treat the result as an estimate, not a certified appraisal. Compare recent sold listings, established references, and a qualified numismatist for valuable or uncertain coins.']
  ];
  const style=document.createElement('style');
  style.textContent='.wc-help-trigger{position:fixed;right:16px;bottom:18px;z-index:1200;width:46px;height:46px;border-radius:15px;border:1px solid #0a84ff;background:#151518;color:#fff;font:900 18px system-ui;box-shadow:0 12px 34px #0009;cursor:pointer}.wc-help-backdrop{position:fixed;inset:0;z-index:1400;display:none;align-items:flex-end;justify-content:center;background:#000c;padding-top:env(safe-area-inset-top)}.wc-help-backdrop.open{display:flex}.wc-help-panel{width:min(100%,720px);max-height:92vh;overflow:auto;background:#101012;color:#fff;border:1px solid #34343a;border-bottom:0;border-radius:28px 28px 0 0;padding:18px 16px calc(26px + env(safe-area-inset-bottom));box-shadow:0 -24px 70px #0009}.wc-help-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.wc-help-head h2{margin:4px 0 0;font:800 22px system-ui}.wc-help-kicker{color:#0a84ff;font:900 11px system-ui;letter-spacing:.14em}.wc-help-close{width:40px;height:40px;border-radius:50%;border:1px solid #3a3a3c;background:#1c1c1e;color:#fff;font-size:22px}.wc-help-intro{color:#aaa;font:13px/1.5 system-ui}.wc-help-video{border:1px dashed #3a3a3c;border-radius:18px;padding:16px;background:#1c1c1e;color:#aaa;font:12px/1.5 system-ui}.wc-help-steps{display:grid;gap:9px;margin-top:14px}.wc-help-step{border:1px solid #2c2c2e;border-radius:16px;padding:13px;background:#18181a}.wc-help-step strong{display:block;color:#4da3ff;font:800 13px system-ui}.wc-help-step span{display:block;margin-top:4px;color:#bbb;font:12px/1.45 system-ui}.wc-help-check{display:flex;gap:9px;align-items:flex-start;margin-top:14px;color:#aaa;font:12px/1.4 system-ui}.wc-help-done{width:100%;margin-top:14px;border:0;border-radius:14px;padding:13px;background:#0a84ff;color:#fff;font:900 14px system-ui}@media(min-width:700px){.wc-help-backdrop{align-items:center;padding:24px}.wc-help-panel{border-bottom:1px solid #34343a;border-radius:28px}}';
  document.head.appendChild(style);
  const back=document.createElement('div'); back.className='wc-help-backdrop';
  back.innerHTML='<section class="wc-help-panel" role="dialog" aria-modal="true" aria-labelledby="wcHelpTitle"><div class="wc-help-head"><div><div class="wc-help-kicker">WHATCOIN · HELP</div><h2 id="wcHelpTitle">How to use WhatCoin</h2></div><button class="wc-help-close" type="button" aria-label="Close help">×</button></div><p class="wc-help-intro">A quick guide to getting a more defensible coin-value estimate. You can skip this and reopen it anytime.</p><div class="wc-help-video"><strong style="color:#fff">Demo video slot ready.</strong><br>The written walkthrough is active now. A short final recording can be added after the interface is locked.</div><div class="wc-help-steps">'+steps.map((s,i)=>'<div class="wc-help-step"><strong>'+(i+1)+'. '+s[0]+'</strong><span>'+s[1]+'</span></div>').join('')+'</div><label class="wc-help-check"><input class="wc-help-dont" type="checkbox"><span>Don’t show this automatically again. Help stays available from the ? button.</span></label><button class="wc-help-done" type="button">Got it</button></section>';
  document.body.appendChild(back);
  const close=()=>{try{if(back.querySelector('.wc-help-dont').checked)localStorage.setItem(HIDE,'1')}catch{};back.classList.remove('open')};
  const open=auto=>{back.classList.add('open');if(auto){try{localStorage.setItem(SEEN,'1')}catch{}}};
  back.querySelector('.wc-help-close').onclick=close; back.querySelector('.wc-help-done').onclick=close; back.onclick=e=>{if(e.target===back)close()};
  const t=document.createElement('button');t.className='wc-help-trigger';t.type='button';t.textContent='?';t.title='How to use WhatCoin';t.setAttribute('aria-label','How to use WhatCoin');t.onclick=()=>open(false);document.body.appendChild(t);
  try{if(localStorage.getItem(SEEN)!=='1'&&localStorage.getItem(HIDE)!=='1')setTimeout(()=>open(true),900)}catch{setTimeout(()=>open(true),900)}
})();